# Clase 1 - Vectores

![title](./Clase1-parte1.png)

![title](./Clase1-parte2.png)

![title](./Clase1-parte3.png)

![title](./Clase1-parte4.png)

![title](./Clase1-parte5.png)

In [2]:
import numpy as np
# numpy es una libreria para realizar todo tipo de operaciones matematicas complejas en Python

# Creamos un vector (array unidimensional), que pertenece a R^3
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [3]:
print(v+w) # adicion de ambos vectores 

[3 4 4]


In [4]:
print(v-w)

[-1 -6  0]


In [5]:
# Multiplicacion por un escalar
print(3*v)

[ 3 -3  6]


In [6]:
# Norma o longitud
print(np.linalg.norm(v))

2.449489742783178


In [1]:
# Producto punto
s = np.dot(v,w)
print(s)

NameError: name 'np' is not defined